name: coral_seg
channels:
  - nvidia
  - conda-forge
  - anaconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=3_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - accelerate=1.8.1=pyhe01879c_0
  - aiohappyeyeballs=2.4.4=py310h06a4308_0
  - aiohttp=3.11.10=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - albucore=0.0.24=pyhd8ed1ab_0
  - albumentations=2.0.8=pyhd8ed1ab_0
  - alsa-lib=1.2.14=h5eee18b_0
  - annotated-types=0.6.0=py310h06a4308_0
  - aom=3.9.1=hac33072_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow=1.3.0=py310h06a4308_0
  - asttokens=3.0.0=py310h06a4308_0
  - async-timeout=5.0.1=py310h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - attrs=24.3.0=py310h06a4308_0
  - aws-c-auth=0.9.3=hef928c7_0
  - aws-c-cal=0.9.13=h2c9d079_1
  - aws-c-common=0.12.6=hb03c661_0
  - aws-c-compression=0.3.1=h8b1a151_9
  - aws-c-event-stream=0.5.7=h28f887f_1
  - aws-c-http=0.10.7=ha8fc4e3_5
  - aws-c-io=0.23.3=hdaf4b65_5
  - aws-c-mqtt=0.13.3=hc63082f_11
  - aws-c-s3=0.11.3=h06ab39a_1
  - aws-c-sdkutils=0.2.4=h8b1a151_4
  - aws-checksums=0.2.7=h8b1a151_5
  - aws-crt-cpp=0.35.4=h8824e59_0
  - aws-sdk-cpp=1.11.606=h20b40b1_10
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.16.0=h75daedc_0
  - azure-storage-common-cpp=12.12.0=h3d7a050_0
  - azure-storage-files-datalake-cpp=12.14.0=hd454692_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_9
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - cffi=1.17.1=py310h1fdaa30_1
  - chardet=4.0.0=py310h06a4308_1003
  - click=8.1.8=py310h06a4308_0
  - comm=0.2.1=py310h06a4308_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cpython=3.10.18=py310hd8ed1ab_0
  - cuda-crt-tools=12.9.86=ha770c72_1
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hbd13f7d_0
  - cuda-cupti=12.9.79=h9ab20c4_0
  - cuda-libraries=11.8.0=0
  - cuda-nvcc-tools=12.9.86=he02047a_1
  - cuda-nvdisasm=12.9.88=hbd13f7d_0
  - cuda-nvrtc=12.9.86=h5888daf_0
  - cuda-nvtx=12.9.79=h5888daf_0
  - cuda-nvvm-tools=12.9.86=he02047a_1
  - cuda-opencl=12.9.19=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.9=3
  - cudnn=9.17.0.29=h1769b22_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_2
  - dataclasses=0.8=pyh6d0b6a4_7
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - double-conversion=3.3.1=h6a678d5_0
  - eval-type-backport=0.2.2=py310h06a4308_1
  - eval_type_backport=0.2.2=pyha770c72_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=7.1.1=gpl_hbbdf940_911
  - fmt=12.1.0=hff5e90c_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.55.3=py310h5eee18b_0
  - freeglut=3.4.0=h8b03031_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.5.0=py310h5eee18b_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - gettext=0.25.1=h5888daf_0
  - gettext-tools=0.25.1=h5888daf_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py310h06a4308_0
  - glib=2.86.2=hbcf1ec1_0
  - glib-tools=2.86.2=hf516916_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - harfbuzz=12.2.0=h15599e2_0
  - hdf5=1.14.6=nompi_h6e4c0c1_102
  - icu=75.1=he02047a_0
  - imageio=2.37.2=py310h7040dfc_0
  - imath=3.1.12=h7955e40_0
  - importlib-metadata=8.5.0=py310h06a4308_0
  - intel-gmmlib=22.9.0=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - ipython_pygments_lexers=1.1.1=py310h06a4308_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - jasper=4.2.5=h1920b20_0
  - jedi=0.19.2=py310h06a4308_0
  - jinja2=3.1.6=py310h06a4308_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - joblib=1.4.2=py310h06a4308_0
  - jupyter_core=5.8.1=py310h06a4308_0
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kaldi=5.5.1112=cpu_h7360626_9
  - kiwisolver=1.4.8=py310h6a678d5_0
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=py310h06a4308_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - level-zero=1.23.1=h84d6215_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarrow=23.0.0=h2c50142_0_cpu
  - libarrow-acero=23.0.0=h635bf11_0_cpu
  - libarrow-compute=23.0.0=h8c2c5c3_0_cpu
  - libarrow-dataset=23.0.0=h635bf11_0_cpu
  - libarrow-substrait=23.0.0=h3f74fd7_0_cpu
  - libasprintf=0.25.1=h8e693c7_0
  - libasprintf-devel=0.25.1=h8e693c7_0
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.11.0=5_h5875eb1_mkl
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.75=h39aace5_0
  - libcblas=3.11.0=5_hfef963f_mkl
  - libclang-cpp19.1=19.1.7=default_hb5137d0_3
  - libclang-cpp20.1=20.1.8=default_hddf928d_0
  - libclang-cpp21.1=21.1.8=default_h99862b1_2
  - libclang13=21.1.8=default_h746c552_2
  - libcrc32c=1.1.2=h6a678d5_0
  - libcublas=12.9.1.4=h9ab20c4_0
  - libcudnn=9.17.0.29=h8ba3bec_0
  - libcudnn-dev=9.17.0.29=hc9053b6_0
  - libcudss=0.7.1.4=h58dd1b1_0
  - libcufft=11.4.1.4=h5888daf_0
  - libcufile=1.14.1.1=4
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.10.19=0
  - libcurl=8.18.0=h4e3cde8_0
  - libcusolver=11.7.5.82=h9ab20c4_1
  - libcusparse=12.5.10.65=h5888daf_1
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h5888daf_0
  - libgettextpo-devel=0.25.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.86.2=h32235b2_0
  - libglu=9.0.3=h60c0c69_1
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.1.0=h767d61c_3
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.73.1=h1e535eb_0
  - libheif=1.19.7=gpl_hc18d805_100
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.3=h47b2149_0
  - liblapack=3.11.0=5_h5e43f62_mkl
  - liblapacke=3.11.0=5_hdba1596_mkl
  - libllvm19=19.1.7=hf7376ad_2
  - libllvm20=20.1.8=hf7376ad_1
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmagma=2.9.0=h9918c94_2
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.9.86=h5888daf_1
  - libnvjpeg=12.4.0.76=h5888daf_0
  - libogg=1.3.5=h27cfd23_1
  - libopencv=4.12.0=headless_py310ha80bd6e_1
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libparquet=23.0.0=h7376487_0_cpu
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.54=h421ea60_0
  - libpq=18.1=h5c52fec_2
  - libprotobuf=6.31.1=h9ef548d_1
  - libre2-11=2025.11.05=h7b12aa8_0
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsystemd0=257.7=h4e0b6ca_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h8261f1e_0
  - libtorch=2.9.1=cuda129_mkl_hf5f578d_303
  - libudev1=257.7=hbe16f8c_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libutf8proc=2.11.3=hfe17d71_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb9d3cd8_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h7b6447c_0
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=21.1.8=h4922eb0_0
  - lxml=6.0.2=py310he6d4be0_2
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib=3.10.0=py310h06a4308_0
  - matplotlib-base=3.10.0=py310hbfdbfaf_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2025.3.0=h0e700b2_463
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=py310h06a4308_0
  - multidict=6.1.0=py310h5eee18b_0
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - nccl=2.29.2.1=h4d09622_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=py310h06a4308_0
  - networkx=3.4.2=py310h06a4308_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - nomkl=2.0=0
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - numexpr=2.14.1=py310h34a7263_101
  - numpy=2.2.6=py310hefbff90_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.12.0=headless_py310h9a9916e_1
  - openexr=3.3.4=h2cd1444_0
  - openfst=1.8.3=h84d6215_3
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.1=h35e630c_1
  - optree=0.14.1=py310hdb19cb5_0
  - orc=2.2.2=h19cb568_0
  - packaging=25.0=py310h06a4308_1
  - pandas=2.3.1=py310h277b779_0
  - pango=1.56.4=hadf4263_0
  - parso=0.8.4=py310h06a4308_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=py310h06a4308_0
  - pillow=11.3.0=py310h7e6dc6c_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.2=h29eaf8c_0
  - platformdirs=4.3.7=py310h06a4308_0
  - ply=3.11=py310h06a4308_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - propcache=0.3.1=py310h5eee18b_0
  - protobuf=6.31.1=py310h565c32f_0
  - psutil=5.9.0=py310h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=hac146a9_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-opencv=4.12.0=headless_py310h604663d_1
  - pyarrow=23.0.0=py310hff52083_0
  - pyarrow-core=23.0.0=py310h923f568_0_cpu
  - pybind11=2.9.2=py310h3c18c91_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.7=py310h06a4308_0
  - pydantic-core=2.33.2=py310hc6f7160_0
  - pygments=2.19.1=py310h06a4308_0
  - pyparsing=3.2.0=py310h06a4308_0
  - pyqt=5.15.10=py310h6a678d5_1
  - pyqt5-sip=12.13.0=py310h5eee18b_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-gil=3.10.18=hd8ed1ab_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py310h5eee18b_0
  - python_abi=3.10=8_cp310
  - pytorch=2.9.1=cuda129_mkl_py310_h1916812_303
  - pytorch-lightning=2.6.1=pyhcf101f3_0
  - pytz=2025.2=py310h06a4308_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - pyzmq=26.2.0=py310h6a678d5_0
  - qt-main=5.15.15=h3c3fd16_6
  - qt6-main=6.9.3=h5c1c036_1
  - rav1e=0.7.1=h8fae777_3
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=h853b02a_0
  - regex=2024.11.6=py310h5eee18b_0
  - requests=2.32.4=py310h06a4308_0
  - responses=0.13.3=pyhd3eb1b0_0
  - s2n=1.6.2=he8a4886_1
  - safetensors=0.5.3=py310h922eef2_0
  - scikit-image=0.25.2=py310h86c3e14_1
  - scikit-learn=1.6.1=py310h6a678d5_0
  - scipy=1.15.2=py310h1d65ade_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.22=h68140b3_0
  - sentry-sdk=2.18.0=py310h06a4308_0
  - setproctitle=1.2.2=py310h5eee18b_2
  - setuptools=78.1.1=py310h06a4308_0
  - simsimd=6.5.0=py310ha75aee5_0
  - sip=6.7.12=py310h6a678d5_1
  - six=1.17.0=py310h06a4308_0
  - sleef=3.9.0=ha0421bc_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.2=h03e3b7b_0
  - sqlite=3.51.2=hbc0de68_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - stringzilla=3.12.5=py310ha75aee5_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.13.3=py310h06a4308_1
  - tbb=2022.3.0=hb700be7_2
  - text-unidecode=1.3=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tifffile=2025.2.18=py310h06a4308_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.0.1=py310h06a4308_0
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - torchvision=0.24.1=cuda129_py310_hb1696bd_1
  - torchvision-extra-decoders=0.0.2=py310haa24be6_5
  - tqdm=4.67.1=py310h2f386ee_0
  - triton=3.5.1=cuda129py310hc5d9a74_0
  - typing=3.10.0.0=py310h06a4308_0
  - typing-inspection=0.4.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py310h5eee18b_1
  - unidecode=1.3.8=py310h06a4308_0
  - urllib3=2.5.0=py310h06a4308_0
  - wandb=0.21.0=py310h69e60fc_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.45=hd8ed1ab_0
  - wcwidth=0.2.13=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxcursor=1.2.3=h9b100fa_0
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxscrnsaver=1.2.4=h9b100fa_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py310h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=py310h06a4308_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiobotocore==2.23.1
      - aioitertools==0.12.0
      - anyio==4.12.1
      - botocore==1.38.46
      - cairocffi==1.7.1
      - cairosvg==2.8.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.2
      - cssselect2==0.8.0
      - datasets==4.0.0
      - defusedxml==0.7.1
      - dill==0.3.8
      - entrypoints==0.4
      - evaluate==0.4.5
      - filelock==3.18.0
      - fsspec==2024.3.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.7
      - idna==3.10
      - ipykernel==6.25.2
      - ipython==8.21.0
      - jmespath==1.0.1
      - jupyter-client==7.4.9
      - multiprocess==0.70.16
      - prompt-toolkit==3.0.51
      - pyarrow-hotfix==0.7
      - s3fs==2024.3.1
      - shellingham==1.5.4
      - tinycss2==1.5.1
      - tokenizers==0.22.2
      - tornado==6.2
      - traitlets==5.9.0
      - transformers==5.0.0
      - typer-slim==0.21.1
      - typing-extensions==4.14.1
      - webencodings==0.5.1
      - wrapt==1.17.2
prefix: /home/linneamw/anaconda3/envs/coral_seg
